searchPath=/liquibase/changelog
changeLogFile=db.changelog-root.yaml
liquibaseSchemaName=public
databaseChangelogTableName=databasechangelog
databaseChangelogLockTableName=databasechangeloglock
logLevel=info
