searchPath=/liquibase/changelog
changeLogFile=db.changelog-root.yaml
url=jdbc:postgresql://db:5432/cemetery_mapping
username=cemetery_app
password=cemetery_app_dev
liquibaseSchemaName=public
databaseChangelogTableName=databasechangelog
databaseChangelogLockTableName=databasechangeloglock
logLevel=info
